store/basicapp/urls.py
from django.urls import path, include
from basicapp import views

app_name = 'basicapp'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login', views.user_login, name='user_login'),
    path('view/', views.viewdb.as_view(), name='view'),
    path('dbms/', views.dbms.as_view(), name='dbms'),
    path('order/', views.createorder, name='order'),
]

store/store/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from basicapp import views

urlpatterns = [
    path('', views.index.as_view(),name='index'),
    path('admin/', admin.site.urls),
    path('harry/', include('basicapp.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special', views.special, name='special'),
    path('edit/<int:id>', views.edit),
    path('update/<int:id>', views.update),
    path('delete/<int:id>', views.bin),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/basicapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class UserProfileInfo(models.Model):
    name = models.CharField(max_length=200,default=None)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture=models.ImageField(upload_to='profile_pics',blank=True)

    def __str__(self):
        return self.user.username

class UserDealers(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE)
    dealer=models.CharField(max_length=200)
    contact = models.TextField(max_length=100, blank=True)

    def __str__(self):
        return self.dealer

class UserStock(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    dealer = models.ForeignKey(UserDealers, on_delete=models.CASCADE)
    item=models.CharField(max_length=200)
    company = models.CharField(max_length=200, blank=True, default=None,null=True)
    rate = models.FloatField(blank=True, default=None, null=True)
    mrp = models.FloatField(blank=True, default=None, null=True)

    def __str__(self):
        return self.item

class RecycleBin(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    dealer = models.ForeignKey(UserDealers, on_delete=models.CASCADE)
    item = models.CharField(max_length=200)
    company = models.CharField(max_length=200, blank=True, default=None,null=True)
    rate = models.FloatField(blank=True, default=None, null=True)
    mrp = models.FloatField(blank=True, default=None, null=True)

    def __str__(self):
        return self.item

store/basicapp/forms.py
from django import forms
from django.contrib.auth.models import User
from basicapp.models import UserProfileInfo,UserDealers,UserStock


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())
    name = forms.CharField(max_length=200)
    class Meta():
        model = User
        fields = ('username', 'email', 'password', 'name')


class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('picture',)

class EntryForm(forms.ModelForm):
    def __init__(self,user,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['dealer'].queryset = UserDealers.objects.filter(owner=user)
    class Meta():
        model=UserStock
        fields = ('item', 'company', 'rate', 'mrp', 'dealer')
        widgets={
            'item': forms.TextInput(attrs={'class': 'form-control'}),
            'dealer': forms.Select(attrs={'class': 'form-control'}),
            'company': forms.TextInput(attrs={'class': 'form-control'}),
            'rate': forms.NumberInput(attrs={'class': 'form-control'}),
            'mrp': forms.NumberInput(attrs={'class': 'form-control'}),
        }


class EditForm(forms.ModelForm):
    class Meta():
        model = UserStock
        fields = ('item', 'company', 'rate', 'mrp')
        widgets = {
            'item': forms.TextInput(),
            'company': forms.TextInput(),
            'rate': forms.NumberInput(),
            'mrp': forms.NumberInput(),
        }

class DealerForm(forms.ModelForm):
    dealer = forms.CharField(max_length=200,widget=forms.TextInput(attrs={'class': 'form-control'}))
    contact = forms.CharField(widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta():
        model=UserDealers
        fields=('dealer','contact')

store/basicapp/views.py
from django.shortcuts import render,redirect
from django.views.generic import View,TemplateView,ListView,DetailView
# Create your views here.
from django.shortcuts import render
from basicapp.forms import UserForm, UserProfileInfoForm,EntryForm,DealerForm,EditForm
from django.contrib import messages
from basicapp.models import UserProfileInfo,UserDealers,UserStock,RecycleBin
# Extra Imports for the Login and Logout Capabilities
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User

# Create your views here.
class index(TemplateView):
    template_name='basicapp/index.html'

@login_required
def special(request):
    # Remember to also set login url in settings.py!
    # LOGIN_URL = '/basic_app/user_login/'
    return HttpResponse("You are logged in. Nice!\n Now you can access your database.")


@login_required
def user_logout(request):
    # Log out the user.
    logout(request)
    # Return to homepage.
    return HttpResponseRedirect(reverse('index'))


def register(request):

    registered = False

    if request.method == 'POST':

        # Get info from "both" forms
        # It appears as one form to the user on the .html page
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileInfoForm(data=request.POST)

        # Check to see both forms are valid
        if user_form.is_valid() and profile_form.is_valid():

            # Save User Form to Database
            user = user_form.save()

            # Hash the password
            user.set_password(user.password)

            # Update with Hashed password
            user.save()

            # Now we deal with the extra info!

            # Can't commit yet because we still need to manipulate
            profile = profile_form.save(commit=False)

            # Set One to One relationship between
            # UserForm and UserProfileInfoForm
            profile.user = user

            # Check if they provided a profile picture
            if 'profile_pic' in request.FILES:
                print('found it')
                # If yes, then grab it from the POST form reply
                profile.profile_pic = request.FILES['profile_pic']

            # Now save model
            profile.save()

            # Registration Successful!
            registered = True

        else:
            # One of the forms was invalid if this else gets called.
            print(user_form.errors, profile_form.errors)

    else:
        # Was not an HTTP post so we just render the forms as blank.
        user_form = UserForm()
        profile_form = UserProfileInfoForm()

    # This is the render and context dictionary to feed
    # back to the registration.html file page.
    return render(request, 'basicapp/register.html',
                  {'user_form': user_form,
                           'profile_form': profile_form,
                           'registered': registered})


def user_login(request):
    if request.method == 'POST':
        # First get the username and password supplied
        username = request.POST.get('username')
        password = request.POST.get('password')

        # Django's built-in authentication function:
        user = authenticate(username=username, password=password)

        # If we have a user
        if user:
            #Check it the account is active
            if user.is_active:
                # Log the user in.
                login(request, user)
                # Send the user back to some page.
                # In this case their homepage.
                return HttpResponseRedirect(reverse('index'))
            else:
                # If account is not active:
                return HttpResponse("Your account is not active.")
        else:
            print("Someone tried to login and failed.")
            print("They used username: {} and password: {}".format(
                username, password))
            return HttpResponse("Invalid login details supplied.")

    else:
        #Nothing has been provided for username or password.
        return render(request, 'basicapp/login.html', {})


class viewdb(View):
    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            itemlist=UserStock.objects.filter(owner__username=request.user.username).order_by('dealer','item')
            contdict={'records': itemlist}
            return render(request, 'basicapp/view.html',contdict)
        else:
            return render(request,'basicapp/login.html')

class dbms(View):
    def get(self,request,*args,**kwargs):
        if request.user.is_authenticated:
            entry_form = EntryForm(request.user, request.POST)
            dealer_form = DealerForm()
            itemlist=UserStock.objects.filter(owner__username=request.user.username).order_by('dealer','item')
            return render(request, 'basicapp/dbms.html', {'entry_form': entry_form, 'dealer_form': dealer_form,'records':itemlist})
        else:
            return render(request, 'basicapp/login.html')
    def post(self,request,*args,**kwargs):
        
        itemlist = UserStock.objects.filter(
        owner__username=request.user.username).order_by('dealer', 'item')
        if 'add_d' in request.POST:
            entry_form = EntryForm(request.user)
            dealer_form = DealerForm(request.POST)
            if dealer_form.is_valid():
                dealer=dealer_form.save(commit=False)
                dealer.owner=request.user
                dealer.save()
        if 'add_e' in request.POST:
            entry_form = EntryForm(request.user, request.POST)
            dealer_form = DealerForm()
            if entry_form.is_valid():
                entry=entry_form.save(commit=False)
                entry.owner=request.user
                if entry.item:
                    entry.item = entry.item.upper()
                if entry.company:
                    entry.company = entry.company.upper()
                entry.save()
        return render(request, 'basicapp/dbms.html', {'entry_form': entry_form, 'dealer_form': dealer_form, 'records': itemlist})

def edit(request,id):
    item = UserStock.objects.get(id=id)
    if item.owner==request.user:
        dealerlist = UserDealers.objects.filter(owner__username=request.user.username)
        return render(request,'basicapp/edit.html',{'row': item,'dealers': dealerlist})
    else:
        return HttpResponse("Access Denied!")

def update(request,id):
    item = UserStock.objects.get(id=id)
    if item.owner==request.user:
        form=EditForm(request.POST,instance=item)
        if form.is_valid():
            print("YES")
            updateform=form.save(commit=False)
            updateform.dealer.dealer=request.POST.get('dealer')
            updateform.user=request.user
            if updateform.item:
                updateform.item = updateform.item.upper()
            if updateform.company:
                updateform.company = updateform.company.upper()
            updateform.save()
            return redirect("/harry/view/")
        else:
            print(form.errors)
        return render(request, 'basicapp/edit.html', {'row': item})
    else:
        return HttpResponse("Access Denied!")

def bin(request,id):
    item = UserStock.objects.get(id=id)
    if item.owner == request.user:
        binitem = RecycleBin(owner=request.user, dealer=item.dealer,item=item.item, company=item.company, rate=item.rate, mrp=item.mrp)
        binitem.save()
        item.delete()
        return redirect("/harry/view/")
    else:
        return HttpResponse("Access Denied!")

def createorder(request):
    if request.user.is_authenticated:
        return render(request, 'basicapp/order.html')
    else:
        return render(request, 'basicapp/login.html')

store/templates/basicapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
        integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
        integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
        crossorigin="anonymous"></script>
    <title>Harry</title>
</head>
<body class="bg-dark">
<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-dark">
<a class="navbar-brand" href="{% url 'index' %}">Harry</a>
<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav"
    aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
<div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:view' %}">View</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:dbms' %}">DBMS</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'basicapp:order' %}">Order</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
        {% else %}
        <li class="nav-item"><a class="nav-link" href="{% url 'basicapp:register' %}">Register</a></li>
        <li class="nav-item"><a class="nav-link" href="{% url 'basicapp:user_login' %}">Login</a></li>
        {% endif %}
    </ul>
</div>
</nav>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark"><a class="navbar-brand" href="{% url 'index' %}">Harry</a>
</nav>
<div>
{% block bodyblock %}
{% endblock bodyblock %}
</div>
</body>
</html>

store/templates/basicapp/dbms.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}
<div class="row">
<div class="col-lg-3 jumbotron">
    <form method="post" enctype="multipart/form-data">
        {{dealer_form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" name="add_d" value="Add Dealer">
    </form>
</div>
<div class="jumbotron col-lg-9 border-success border-left">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row">
        {% for field in entry_form %}
        <div class="col-lg-6">
            {{ field.label_tag }}{{ field }}
        </div>
        {% endfor %}
        <input type="submit" class="btn btn-primary mt-4 ml-1" name="add_e" value="Add entry">
        </div>
    </form>
</div></div>
{% if records %}
<div class="table-responsive-lg">
    <table class="table table-dark">
        <thead class="thread-dark">
            <th>Item</th>
            <th>Dealer</th>
            <th>Rate</th>
            <th>MRP</th>
            <th>Company</th>
            <th>Actions</th>
        </thead>
        {% for row in records %}
        <tr>
            <td>{{row.item}}</td>
            <td>{{row.dealer}}</td>
            <td>{{row.rate}}</td>
            <td>{{row.mrp}}</td>
            <td>{{row.company}}</td>
            <td><a href="/edit/{{ row.id }}" class="p-2">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="aqua" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                </svg></a>  <a href="/delete/{{ row.id }}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="red" xmlns="http://www.w3.org/2000/svg">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
            </svg></a></td>
        </tr>
        {% endfor %}
    </table>
</div>
{% else %}
<h1>No Records Found!</h1>
{% endif %}
{% endblock bodyblock %}

store/templates/basicapp/dealer.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}
<div class="jumbotron m-2 col-sm-2">
    <form method="post" enctype="multipart/form-data">
        {{dealer_form.as_p}}
        {% csrf_token %}
        <input type="submit" class="btn btn-primary" name="Add" value="Add Dealer">
    </form>
</div>
{% endblock bodyblock %}

store/templates/basicapp/edit.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}
<div class="jumbotron">
    <form method="POST" action="/update/{{row.id}}" enctype="multipart/form-data">
        {% csrf_token %}
        <label for="item" class="form-group">Item:</label>
        <input type="text" class="form-control" name="item" value="{{ row.item }}"/>
        <label for="company" class="form-group">Company:</label>
        <input type="text" class="form-control" name="company" value="{{ row.company }}" />
        <label for="rate" class="form-group">Rate:</label>
        <input type="number" name="rate" class="form-control" value="{{ row.rate }}">
        <label for="mrp" class="form-group">MRP:</label>
        <input type="number" name="mrp" class="form-control" value="{{ row.mrp }}">
        <label for="dealer" class="form-group">Dealer:</label>
        <select name="dealer" class="form-control">
            {% for s in dealers %}
                {% ifequal s row.dealer %}
                    <option value="{{s}}" selected>{{s}}</option>
                {% else %}
                    <option value="{{s}}">{{s}}</option>
                {% endifequal %}
            {% endfor %}
        </select>
        <button type="submit" class="btn btn-primary mt-4 ml" name="edit_e">Update</button>
    </form>
</div>
{% endblock bodyblock %}

store/templates/basicapp/index.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}
<div class="text-white">
<h1>Welcome Retailer</h1><br>
<h3>Register here and keep track of your records and make sure to get all items while making an order.</h3><br>
<h3>Login to Access your records.</h3><br>
<h5>Arigato Gozaimasu!</h5>
</div>
{% endblock bodyblock %}

store/templates/basicapp/login.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}
<div class="jumbotron">
    <h1>Please login</h1>
    <form action="{% url 'basicapp:user_login' %}" method="POST">
        {% csrf_token %}
        <label for="username">Username:</label>
        <input class="form-control" type="text" name="username" placeholder="Enter Username">
        <label for="password">Password:</label>
        <input class="form-control mb-3" type="password" name="password" placeholder="Enter Password">
        <input class="btn btn-primary" type="submit" value="Login"> OR
        <a class="btn btn-outline-success" href="{% url 'basicapp:register' %}">Sign-Up</a>
    </form>
</div>
{% endblock bodyblock %}

store/templates/basicapp/order.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}
<h1 class="text-white">Order</h1>

{% endblock bodyblock %}

store/templates/basicapp/register.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}
<div class="jumbotron">
    {% if registered %}
    <h1>Thank u for registration.<br>
    Now you can login.</h1>
    {% else %}
    <h1>Register Here!</h1><br>
    <h3>Fill out the form</h3><br>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ profile_form.as_p }}
        <input class="btn btn-primary" type="submit" name="" value="Register">
    </form>
    {% endif %}
</div>

{% endblock bodyblock %}

store/templates/basicapp/view.html
{% extends 'basicapp/base.html' %}
{% block bodyblock %}

{% if records %}

<!-- {% for row in dealers %}
    <h2> {{row}} </h2>
{% endfor %} -->

<div class="table-responsive-lg">
<table class="table table-dark">
    <thead class="thead-dark">
        <th>Item</th>
        <th>Dealer</th>
        <th>Rate</th>
        <th>MRP</th>
        <th>Company</th>
        <th>Actions</th>
    </thead>
    {% for row in records %}
        <tr>
            <td>{{row.item}}</td>
            <td>{{row.dealer}}</td>
            <td>{{row.rate}}</td>
            <td>{{row.mrp}}</td>
            <td>{{row.company}}</td>
            <td><a href="/edit/{{ row.id }}" class="p-2">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-pencil" fill="aqua" xmlns="http://www.w3.org/2000/svg">
                <path fill-rule="evenodd" d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5L13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175l-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z" />
                </svg></a>  <a href="/delete/{{ row.id }}"><svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-trash" fill="red" xmlns="http://www.w3.org/2000/svg">
                <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z" />
                <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4L4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z" />
            </svg></a></td>
        </tr>
    {% endfor %}
</table>
</div>
{% else %}
<h1>No Records Found!</h1>
{% endif %}
{% endblock bodyblock %}